<?php

$testpathhttp = [
    [
        "data" => "https://test.fr/usr/local/www/../site/../../tmp/index.php",
        "path" => "https://test.fr/usr/tmp/index.php",
        "parent" => "https://test.fr/usr/tmp",
        "absolutparent" => "https://test.fr/usr/tmp",
        "absolutpath" => "https://test.fr/usr/tmp/index.php",
        "name" => "index.php",
        "namedisk" => "https://test.fr",
        "parentin" => "https://test.fr/usr/local/www/../site/../../tmp/index.php",
    ],
    [
        "data" => "https://test.fr/usr/local/www/../../../../../../site/../../tmp/index.php",
        "path" => "https://test.fr/tmp/index.php",
        "parent" => "https://test.fr/tmp",
        "absolutparent" => "https://test.fr/tmp",
        "absolutpath" => "https://test.fr/tmp/index.php",
        "name" => "index.php",
        "namedisk" => "https://test.fr",
        "parentin" => "https://test.fr/usr/local/www/../../../../../../site/../../tmp/index.php",
    ],
    [
        "data" => "https://test.fr",
        "path" => "https://test.fr",
        "parent" => "https://test.fr",
        "absolutparent" => "https://test.fr",
        "absolutpath" => "https://test.fr/",
        "name" => "",
        "namedisk" => "https://test.fr",
        "parentin" => "https://test.fr",
    ],
];

$testpatrelatif = [
    [
        "data" => "../index.php",
        "path" => "./../index.php",
        "parent" => "./..",
        "absolutparent" => "",
        "absolutpath" => "",
        "name" => "",
        "namedisk" => "",
        "parentin" => "../index.php",
    ],
    [
        "data" => "./../index.php",
        "path" => "./../index.php",
        "parent" => "./..",
        "absolutparent" => "",
        "absolutpath" => "",
        "name" => "",
        "namedisk" => "",
        "parentin" => "./../index.php",
    ],
    [
        "data" => "./../../index.php",
        "path" => "./../../index.php",
        "parent" => "./../..",
        "absolutparent" => "",
        "absolutpath" => "",
        "name" => "",
        "namedisk" => "",
        "parentin" => "./../../index.php",
    ],
    [
        "data" => "./../../index.php",
        "path" => "./../../index.php",
        "parent" => "./../..",
        "absolutparent" => "",
        "absolutpath" => "",
        "name" => "",
        "namedisk" => "",
        "parentin" => "./../../index.php",
    ],
    [
        "data" => "../site/../../tmp/../index.php",
        "path" => "./../../index.php",
        "parent" => "./../..",
        "absolutparent" => "",
        "absolutpath" => "",
        "name" => "",
        "namedisk" => "",
        "parentin" => "../site/../../tmp/../index.php",
    ],
    [
        "data" => "./../site/../../tmp/../index.php",
        "path" => "./../../index.php",
        "parent" => "./../..",
        "absolutparent" => "",
        "absolutpath" => "",
        "name" => "",
        "namedisk" => "",
        "parentin" => "./../site/../../tmp/../index.php",
    ],
    [
        "data" => "./../../css/style.css",
        "path" => "./../../css/style.css",
        "parent" => "./../../css",
        "absolutparent" => "",
        "absolutpath" => "",
        "name" => "",
        "namedisk" => "",
        "parentin" => "./../../css/style.css",
    ],
    [
        "data" => "./../css/tabtest.css",
        "path" => "./../css/tabtest.css",
        "parent" => "./../css",
        "absolutparent" => "",
        "absolutpath" => "",
        "name" => "",
        "namedisk" => "",
        "parentin" => "./../css/tabtest.css",
    ],
    [
        "data" => "../..",
        "path" => "./../..",
        "parent" => "./../..",
        "absolutparent" => "",
        "absolutpath" => "",
        "name" => "",
        "namedisk" => "",
        "parentin" => "../..",
    ],
    [
        "data" => "..",
        "path" => "./..",
        "parent" => "./..",
        "absolutparent" => "",
        "absolutpath" => "",
        "name" => "",
        "namedisk" => "",
        "parentin" => "..",
    ],
    [
        "data" => "./../..",
        "path" => "./../..",
        "parent" => "./../..",
        "absolutparent" => "",
        "absolutpath" => "",
        "name" => "",
        "namedisk" => "",
        "parentin" => "./../..",
    ],
    [
        "data" => "./..",
        "path" => "./..",
        "parent" => "./..",
        "absolutparent" => "",
        "absolutpath" => "",
        "name" => "",
        "namedisk" => "",
        "parentin" => "./..",
    ],
];

$testpath = [
    [
        "data" => "/usr/local/www/../site/../../tmp/index.php",
        "path" => "/usr/tmp/index.php",
        "parent" => "/usr/tmp",
        "absolutparent" => "",
        "absolutpath" => "",
        "name" => "",
        "namedisk" => "",
        "parentin" => "/usr/local/www/../site/../../tmp/index.php",
    ],
    [
        "data" => "/usr/local/www/../../../../../../site/../../tmp/index.php",
        "path" => "/tmp/index.php",
        "parent" => "/tmp",
        "absolutparent" => "/tmp",
        "absolutpath" => "/tmp/index.php",
        "name" => "index.php",
        "namedisk" => "/",
        "parentin" => "/usr/local/www/../../../../../../site/../../tmp/index.php",
    ],
    [
        "data" => "c:\usr\local\www\..\site\..\..\tmp\index.php",
        "path" => "c:\usr\tmp\index.php",
        "parent" => "c:\usr\tmp",
        "absolutparent" => "c:\usr\tmp",
        "absolutpath" => "c:\usr\tmp/\index.php",
        "name" => "\index.php",
        "namedisk" => "c:",
        "parentin" => "c:\usr\local\www\..\site\..\..\tmp\index.php",
    ],
    [
        "data" => "c:\usr\local\www\..\..\..\..\..\..\site\..\..\tmp\index.php",
        "path" => "c:\tmp\index.php",
        "parent" => "c:\tmp",
        "absolutparent" => "c:\tmp",
        "absolutpath" => "c:\tmp/\index.php",
        "name" => "\index.php",
        "namedisk" => "c:",
        "parentin" => "c:\usr\local\www\..\..\..\..\..\..\site\..\..\tmp\index.php",
    ],
    [
        "data" => "c:",
        "path" => "c:",
        "parent" => "c:",
        "absolutparent" => "c:",
        "absolutpath" => "c:/",
        "name" => "",
        "namedisk" => "c:",
        "parentin" => "c:",
    ],
    [
        "data" => "/",
        "path" => "/",
        "parent" => "/",
        "absolutparent" => "/",
        "absolutpath" => "//",
        "name" => "",
        "namedisk" => "/",
        "parentin" => "/",
    ],
];
